# This is a basic workflow to help you get started with Actions

name: SSH OpenWRT

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# inputs: 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: andrewtwydell/ssh
              # You may pin to the exact commit or the version.
              # uses: AndrewTwydell/ssh-workflow@f705bd28f2f7dec5d4b2f98ab34367d17678fcf4
            uses: AndrewTwydell/ssh-workflow@1.0.0
            env: 
              HOST: ${{ github.secrets.HOST }}
              PORT: ${{ github.secrets.PORT }}
              USER: ${{ github.secrets.USER }}
              PASSWORD: ${{ github.secrets.PASSWORD }}
            with:
              # SSH Host
              host: 188.134.65.67 # default is 
              # User name
              user: root # default is 
              # User Password
              password: 999 # default is 
              # Script to Run
              script: uci show network # default is 
    # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
